import { initializeApp } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import { getDatabase, ref, get, set } from "https://www.gstatic.com/firebasejs/11.10.0/firebase-database.js";
import { firebaseConfig } from "./firebase-config.js";
const db=getDatabase(initializeApp(firebaseConfig));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={events:[],tests:[],week:0,email:"",key:"",icsText:"",url:""};
const titles={rooster:"Rooster",toetsen:"Toetsen",instellingen:"Instellingen"};
const esc=x=>String(x??"").replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function key(v){return btoa(unescape(encodeURIComponent(String(v).trim().toLowerCase()))).replace(/[+/=]/g,"_")}
function dbref(){return ref(db,`accounts/${S.key}`)}
function setStatus(t,err=false){$("#status").textContent=t;$("#status").className=`status ${err?'error':''}`}
function dayKey(d){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Amsterdam",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function time(d){return new Intl.DateTimeFormat("nl-NL",{timeZone:"Europe/Amsterdam",hour:"2-digit",minute:"2-digit"}).format(d)}
function monday(d){const x=new Date(d);x.setHours(12,0,0,0);const n=x.getDay()||7;x.setDate(x.getDate()-n+1);return x}
function dateTime(t){return new Date(`${t.date}T${t.start||"00:00"}:00`)}
function fmt(d){return new Intl.DateTimeFormat("nl-NL",{day:"numeric",month:"short",timeZone:"Europe/Amsterdam"}).format(d)}
function parseDate(v){const m=String(v||"").match(/^(\d{4})(\d{2})(\d{2})T?(\d{2})?(\d{2})?(\d{2})?(Z)?$/);if(!m)return null;const[,Y,M,D,h="00",mi="00",s="00",z]=m;return z?new Date(Date.UTC(+Y,+M-1,+D,+h,+mi,+s)):new Date(+Y,+M-1,+D,+h,+mi,+s)}
function unfold(s){return s.replace(/\r?\n[ \t]/g,"")}
function val(lines,n){const l=lines.find(x=>x.toUpperCase().startsWith(n+":")||x.toUpperCase().startsWith(n+";"));return l?l.slice(l.indexOf(":")+1):""}
function unesc(v){return String(v||"").replace(/\\n/g,"\n").replace(/\\,/g,",").replace(/\\;/g,";").replace(/\\\\/g,"\\")}
function parseICS(text){const L=unfold(text).split(/\r?\n/),out=[];let cur=null;for(const l of L){if(l.trim()==="BEGIN:VEVENT")cur=[];else if(l.trim()==="END:VEVENT"){if(cur){const st=parseDate(val(cur,"DTSTART"));if(st){const en=parseDate(val(cur,"DTEND"))||new Date(st.getTime()+50*60000);const summary=unesc(val(cur,"SUMMARY")||"Les"),loc=unesc(val(cur,"LOCATION")),desc=unesc(val(cur,"DESCRIPTION"));const subject=unesc((desc.match(/(?:vak|subject)[:=]\s*([^\\n]+)/i)||[])[1]||summary).trim();out.push({id:val(cur,"UID")||crypto.randomUUID(),start:st,end:en,subject,teacher:"",room:loc,summary,description:desc})}}cur=null}else if(cur)cur.push(l)}return out}
function testTypeLabel(t){return t==="small"?"Kleine toets":t==="big"?"Grote toets / toets":"Les"}
function mergedEvents(){return S.events.map(e=>{const m=S.tests.filter(t=>String(t.subject).trim().toLowerCase()===String(e.subject).trim().toLowerCase()&&dayKey(dateTime(t))===dayKey(e.start));if(!m.length)return e;const t=m.find(x=>Math.abs(dateTime(x)-e.start)<7200000)||m[0];return {...e,assessment:t.type,assessmentData:t}})}
function combinedForDay(key){const lessons=mergedEvents().filter(e=>dayKey(e.start)===key);const tests=S.tests.filter(t=>dayKey(dateTime(t))===key && !lessons.some(e=>e.assessmentData?.id===t.id));return [...lessons.map(e=>({kind:"lesson",item:e,at:e.start})),...tests.map(t=>({kind:"test",item:t,at:dateTime(t)}))].sort((a,b)=>a.at-b.at)}
function render(){const base=monday(new Date());base.setDate(base.getDate()+S.week*7);const sun=new Date(base);sun.setDate(base.getDate()+6);$("#week").textContent=(S.week===0?"Deze week · ":"")+`${fmt(base)} – ${fmt(sun)}`;const names=["maandag","dinsdag","woensdag","donderdag","vrijdag","zaterdag","zondag"];const grid=$("#grid");grid.innerHTML="";let count=0;for(let i=0;i<7;i++){const d=new Date(base);d.setDate(base.getDate()+i);const k=dayKey(d);const items=combinedForDay(k);count+=items.length;const col=document.createElement("div");col.className="day";col.innerHTML=`<div class="day-head ${k===dayKey(new Date())?'today':''}"><strong>${names[i]}</strong><span>${d.getDate()}/${d.getMonth()+1}</span></div>`;if(!items.length)col.insertAdjacentHTML("beforeend","<div class=none>Geen lessen</div>");for(const x of items){const e=x.item;const isT=x.kind==="test";const type=isT?e.type:(e.assessment||"");const c=type==="small"?"small-test":type==="big"?"big-test":"";const b=document.createElement("button");b.className=`lesson ${c}`;b.innerHTML=`<div class="lesson-time">${time(x.at)}${e.end&&!isT?`–${time(e.end)}`:""}</div><strong>${esc(e.subject)}</strong>${isT?`<span class="test-tag">${testTypeLabel(e.type)}</span>`:""}${e.room&&!isT?`<small>${esc(e.room)}</small>`:""}`;b.onclick=()=>isT?openTest(e):openLesson(e);col.appendChild(b)}grid.appendChild(col)}$("#empty").classList.toggle("hidden",count>0||S.events.length>0||S.tests.length>0);renderTests()}
function openLesson(e){$("#modalBadge").textContent=e.assessment?testTypeLabel(e.assessment):"Les";$("#modalBadge").className=`badge ${e.assessment||""}`;$("#modalTitle").textContent=e.subject;$("#modalDate").textContent=`${new Intl.DateTimeFormat("nl-NL",{dateStyle:"full"}).format(e.start)} · ${time(e.start)} – ${time(e.end)}`;let b=`<div><span>Locatie</span><strong>${esc(e.room||"-")}</strong></div>`;if(e.assessmentData){const t=e.assessmentData;b+=`<div><span>Soort</span><strong>${testTypeLabel(t.type)}</strong></div>${t.weight?`<div><span>Weging</span><strong>${esc(t.weight)}</strong></div>`:""}${t.description?`<div class="desc"><span>Omschrijving</span><strong>${esc(t.description).replace(/\n/g,"<br>")}</strong></div>`:""}`}$("#modalBody").innerHTML=b;$("#modal").classList.remove("hidden")}
function openTest(t){openLesson({subject:t.subject,start:dateTime(t),end:t.end?new Date(`${t.date}T${t.end}:00`):dateTime(t),room:"",assessment:t.type,assessmentData:t})}
function renderTests(){const b=$("#tests");if(!S.tests.length){b.innerHTML='<div class="none wide-none">Nog geen toetsen opgeslagen.</div>';return}b.innerHTML=[...S.tests].sort((a,b)=>dateTime(a)-dateTime(b)).map(t=>`<button class="test-line ${t.type}" data-id="${t.id}"><i></i><span><strong>${esc(t.subject)}</strong><small>${esc(t.date)} · ${esc(t.start)}</small></span><em>${testTypeLabel(t.type)}</em></button>`).join("");b.querySelectorAll(".test-line").forEach(x=>x.onclick=()=>openTest(S.tests.find(t=>t.id===x.dataset.id)))}
async function save(){await set(dbref(),{email:S.email,calendarUrl:S.url,icsText:S.icsText,tests:S.tests,updatedAt:Date.now()})}
async function restore(){try{const s=await get(dbref());if(!s.exists()){setStatus("Je account is aangemaakt. Voeg je iCalendar-link toe.");return}const d=s.val()||{};S.url=d.calendarUrl||"";S.icsText=d.icsText||"";S.tests=Array.isArray(d.tests)?d.tests:Object.values(d.tests||{});$("#calendarUrl").value=S.url;if(S.icsText){S.events=parseICS(S.icsText);setStatus(`${S.events.length} lessen en ${S.tests.length} toetsen geladen.`)}else setStatus(`${S.tests.length} opgeslagen toetsen geladen.`);render()}catch(e){setStatus("Firebase kon het account niet laden. Controleer de openbare Rules.",true)}}
async function loadICS(text){S.icsText=text;S.events=parseICS(text);if(!S.events.length)throw Error("Geen lessen gevonden");await save();setStatus(`${S.events.length} lessen geladen en opgeslagen in Firebase.`);S.week=0;render()}
async function loadUrl(){let u=$("#calendarUrl").value.trim();if(!u)return setStatus("Plak eerst je Somtoday iCalendar-link.",true);u=u.replace(/^webcal:\/\//i,"https://");S.url=u;setStatus("Rooster ophalen…");try{const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw Error(`HTTP ${r.status}`);await loadICS(await r.text())}catch(e){await save().catch(()=>{});setStatus("Somtoday blokkeert het directe ophalen vanuit de browser (CORS). Gebruik daarom '.ics importeren' om je rooster hier te laden. Je link blijft wel per account bewaard.",true)}}
function openTab(t){$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.tab===t));$$('.panel').forEach(p=>p.classList.toggle('active',p.id===t));$("#title").textContent=titles[t];$("#crumb").textContent=titles[t]}
$("#loginForm").onsubmit=async e=>{e.preventDefault();S.email=$("#email").value.trim();if($("#remember").checked)localStorage.setItem("rosterEmail",S.email);else localStorage.removeItem("rosterEmail");localStorage.setItem("currentEmail",S.email);S.key=key(S.email);$("#login").classList.add('hidden');$("#app").classList.remove('hidden');$("#userEmail").textContent=S.email;$("#settingsEmail").textContent=S.email;await restore();try{await get(ref(db,'health'));$("#dbStatus").textContent='Bereikbaar';$(".side-status i").classList.add('ok');$("#dbPill").textContent='Bereikbaar';$("#dbPill").classList.add('green')}catch{}};
$("#logout").onclick=()=>{location.reload()};$("#schoolClear").onclick=()=>{};const saved=localStorage.getItem('rosterEmail');if(saved)$("#email").value=saved;
$$('.nav').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));$("#prev").onclick=()=>{S.week--;render()};$("#next").onclick=()=>{S.week++;render()};$("#load").onclick=loadUrl;$("#ics").onchange=async e=>{const f=e.target.files?.[0];if(f)try{await loadICS(await f.text())}catch(err){setStatus(err.message,true)}};
function showTest(){ $("#testModal").classList.remove('hidden');$("#tDate").valueAsDate=new Date();$("#tStart").value='08:00'}$("#addTest").onclick=showTest;function closeTest(){$("#testModal").classList.add('hidden')}$("#closeTest").onclick=closeTest;$("#cancelTest").onclick=closeTest;$("#testBackdrop").onclick=closeTest;
$("#testForm").onsubmit=async e=>{e.preventDefault();const t={id:crypto.randomUUID(),subject:$("#tSubject").value.trim(),date:$("#tDate").value,start:$("#tStart").value,end:$("#tEnd").value,type:$("#tType").value,weight:$("#tWeight").value.trim(),description:$("#tDescription").value.trim()};S.tests.push(t);try{await save();render();closeTest();setStatus('Toets opgeslagen in Firebase.')}catch{S.tests.pop();setStatus('Toets opslaan is mislukt.',true)}};
$("#closeModal").onclick=()=>$("#modal").classList.add('hidden');$("#backdrop").onclick=()=>$("#modal").classList.add('hidden');document.addEventListener('keydown',e=>{if(e.key==='Escape'){$("#modal").classList.add('hidden');$("#testModal").classList.add('hidden')}});$("#databaseUrl").textContent=firebaseConfig.databaseURL;
